CREATE TABLE unde_users(
id VARCHAR2(100) PRIMARY KEY, 
pwd VARCHAR2(100) NOT NULL, 
email VARCHAR2(100) NOT NULL,
regdate DATE,
answer NUMBER NOT NULL,
aw VARCHAR2(1000) NOT NULL
);

CREATE SEQUENCE unde_users_seq NOCACHE;